apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: scenario2-prod
spec:
  type: brokered
  plan: scenario2-prod
  endpoints:
    - name: messaging
      service: messaging
    - name: console
      service: console
      expose:
        type: route
        routeTlsTermination: reencrypt
        routeServicePort: https
      cert:
        provider: openshift
