apiVersion: admin.enmasse.io/v1beta2
kind: AddressSpacePlan
metadata:
  labels:
    app: enmasse
  name: scenario2-prod
  namespace: amq-online-infra
spec:
  displayName: Scenario2 PROD
  displayOrder: 0
  addressSpaceType: brokered
  infraConfigRef: scenario2-infra-config
  addressPlans:
  - scenario2-queue
  - scenario2-topic
  resourceLimits:
    broker: 20
