apiVersion: admin.enmasse.io/v1beta2
kind: AddressSpacePlan
metadata:
  labels:
    app: enmasse
  name: scenario2-dev
  namespace: amq-online-infra
spec:
  displayName: Scenario2 DEV
  displayOrder: 0
  addressSpaceType: brokered
  infraConfigRef: scenario2-infra-config-non-prod
  addressPlans:
  - scenario2-queue
  - scenario2-topic
  resourceLimits:
    broker: 2
